use super::ToolKind;

impl ToolKind {
    pub(super) const fn name(self) -> &'static str {
        match self {
            Self::Whoami => "whoami",
            Self::ListWorkspaces => "list_workspaces",
            Self::CreateWorkspace => "create_workspace",
            Self::ListProjects => "list_projects",
            Self::ListObjects => "list_objects",
            Self::GetRetention => "get_retention",
            Self::ListInboxes => "list_inboxes",
            Self::ListShares => "list_shares",
            Self::ListPreviews => "list_previews",
            Self::CreateProject => "create_project",
            Self::UploadFile => "upload_file",
            Self::DownloadFile => "download_file",
            Self::DeleteObject => "delete_object",
            Self::CreateShare => "create_share",
            Self::RevokeShare => "revoke_share",
            Self::CreatePreview => "create_preview",
            Self::RevokePreview => "revoke_preview",
            Self::CreateInbox => "create_inbox",
            Self::RevokeInbox => "revoke_inbox",
            Self::SetRetention => "set_retention",
            Self::ClearRetention => "clear_retention",
            Self::DeployWebYard => "deploy_web_yard",
            Self::ListWebYards => "list_web_yards",
            Self::ListYardDeploys => "list_yard_deploys",
            Self::ListYardEnvironments => "list_yard_environments",
            Self::GetYardAccess => "get_yard_access",
            Self::SetYardVisibility => "set_yard_visibility",
            Self::GrantYardAccess => "grant_yard_access",
            Self::RevokeYardAccess => "revoke_yard_access",
            Self::ListYardGuestInvites => "list_yard_guest_invites",
            Self::CreateYardGuestInvite => "create_yard_guest_invite",
            Self::RevokeYardGuestInvite => "revoke_yard_guest_invite",
            Self::ListYardManagementRoles => "list_yard_management_roles",
            Self::SetYardManagementRole => "set_yard_management_role",
            Self::RevokeYardManagementRole => "revoke_yard_management_role",
            Self::GetYardApplicationPolicy => "get_yard_application_policy",
            Self::SetYardApplicationPolicy => "set_yard_application_policy",
            Self::SetYardAccessRoles => "set_yard_access_roles",
            Self::ListYardSessions => "list_yard_sessions",
            Self::RevokeYardSession => "revoke_yard_session",
            Self::RollbackWebYard => "rollback_web_yard",
            Self::DeleteWebYard => "delete_web_yard",
        }
    }
}
