// Generated by scripts/openapi/generate.mjs. Do not edit.

import type { JsonValue } from "./index.mjs";

export interface Schemas {
  readonly Identifier: string;
  readonly Cursor: string;
  readonly Slug: string;
  readonly IsoTimestamp: string;
  readonly UnixMilliseconds: number;
  readonly BlobyardUri: string;
  readonly CapabilityToken: string;
  readonly Url: string;
  readonly TransferUrl: string;
  readonly EmptyResult: Readonly<Record<string, never>>;
  readonly HealthResult: Readonly<{ readonly status: "ok"; readonly version: string }>;
  readonly ExchangeBootstrapTokenResult: Readonly<{
    readonly accessToken: Schemas["CapabilityToken"];
    readonly scopes: readonly string[];
    readonly webYardOrigin: string;
    readonly workspace: Schemas["Slug"];
  }>;
  readonly WorkspaceSummary: Readonly<{
    readonly id: Schemas["Identifier"];
    readonly name: string;
    readonly slug: Schemas["Slug"];
  }>;
  readonly WorkspacePage: Readonly<{
    readonly items: readonly Schemas["WorkspaceSummary"][];
    readonly nextCursor: Schemas["Cursor"] | null;
  }>;
  readonly ProjectSummary: Readonly<{
    readonly id: Schemas["Identifier"];
    readonly name: string;
    readonly slug: Schemas["Slug"];
    readonly workspaceSlug: Schemas["Slug"];
  }>;
  readonly ProjectPage: Readonly<{
    readonly items: readonly Schemas["ProjectSummary"][];
    readonly nextCursor: Schemas["Cursor"] | null;
  }>;
  readonly TokenPair: Readonly<{
    readonly accessToken: Schemas["CapabilityToken"];
    readonly expiresInSeconds: number;
    readonly refreshToken: Schemas["CapabilityToken"];
  }>;
  readonly DeviceStartResult: Readonly<{
    readonly deviceCode: Schemas["CapabilityToken"];
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly pollIntervalSeconds: number;
    readonly userCode: string;
    readonly verificationUri: Schemas["Url"];
  }>;
  readonly DevicePollResult:
    | Readonly<{ readonly status: "pending" | "slow_down" | "denied" | "expired" }>
    | Readonly<{ readonly status: "approved"; readonly tokens: Schemas["TokenPair"] }>;
  readonly WhoAmIResult: Readonly<{
    readonly defaultWorkspace: Schemas["WorkspaceSummary"];
    readonly displayName: string;
    readonly email?: string;
    readonly principalId: Schemas["Identifier"];
    readonly principalType: "cli" | "ci";
    readonly scopes: readonly string[];
  }>;
  readonly MachineTokenResult: Readonly<{
    readonly accessToken: Schemas["CapabilityToken"];
    readonly expiresInSeconds: number;
    readonly scopes: readonly string[];
  }>;
  readonly SignedHeader: Readonly<{ readonly name: string; readonly value: string }>;
  readonly UploadPartGrant: Readonly<{
    readonly partNumber: number;
    readonly uploadUrl: Schemas["TransferUrl"];
  }>;
  readonly RequestUploadResult: Readonly<{
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly headers: readonly Schemas["SignedHeader"][];
    readonly partSizeBytes: number | null;
    readonly strategy: "single" | "multipart";
    readonly uploadId: Schemas["Identifier"];
    readonly uploadUrl: Schemas["TransferUrl"] | null;
  }>;
  readonly RequestUploadPartsResult: Readonly<{
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly parts: readonly Schemas["UploadPartGrant"][];
  }>;
  readonly CompleteUploadResult: Readonly<{
    readonly checksumSha256: string;
    readonly sizeBytes: number;
    readonly uri: Schemas["BlobyardUri"];
  }>;
  readonly UploadStatusResult: Readonly<{
    readonly completedParts: readonly number[];
    readonly state:
      "requested" | "uploading" | "completing" | "complete" | "aborted" | "expired" | "failed";
  }>;
  readonly DownloadResult: Readonly<{
    readonly checksumSha256: string;
    readonly downloadUrl: Schemas["TransferUrl"];
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly filename: string;
    readonly sizeBytes: number;
  }>;
  readonly ObjectSummary: Readonly<{
    readonly availability: "available" | "deleted" | "pending" | "unavailable";
    readonly createdAt: Schemas["IsoTimestamp"];
    readonly filename: string;
    readonly sizeBytes: number;
    readonly source: "ci" | "cli" | "inbox" | "preview" | "web";
    readonly uri: Schemas["BlobyardUri"];
  }>;
  readonly ObjectPage: Readonly<{
    readonly items: readonly Schemas["ObjectSummary"][];
    readonly nextCursor: Schemas["Cursor"] | null;
  }>;
  readonly DeleteObjectResult: Readonly<{
    readonly deleted: true;
    readonly uri: Schemas["BlobyardUri"];
  }>;
  readonly CreateShareResult: Readonly<{
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly id: Schemas["Identifier"];
    readonly notificationStatus:
      "captured" | "deduplicated" | "failed" | "not_requested" | "queued";
    readonly shareUrl: Schemas["Url"];
  }>;
  readonly ShareSummary: Readonly<{
    readonly consumedCount: number;
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly id: Schemas["Identifier"];
    readonly maximumDownloads: number | null;
    readonly status: "active" | "expired" | "exhausted" | "revoked" | "unavailable";
  }>;
  readonly SharePage: Readonly<{
    readonly items: readonly Schemas["ShareSummary"][];
    readonly nextCursor: Schemas["Cursor"] | null;
  }>;
  readonly ShareMetadata: Readonly<{
    readonly contentTypeClass: string;
    readonly downloadAvailable: boolean;
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly filename: string;
    readonly sizeBytes: number;
  }>;
  readonly CreatePreviewResult: Readonly<{
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly id: Schemas["Identifier"];
    readonly previewUrl: Schemas["Url"];
  }>;
  readonly PreviewSummary: Readonly<{
    readonly createdAt: Schemas["IsoTimestamp"];
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly id: Schemas["Identifier"];
    readonly status: "active" | "expired" | "exhausted" | "revoked";
  }>;
  readonly PreviewPage: Readonly<{
    readonly items: readonly Schemas["PreviewSummary"][];
    readonly nextCursor: Schemas["Cursor"] | null;
  }>;
  readonly CreateInboxResult: Readonly<{
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly id: Schemas["Identifier"];
    readonly inboxUrl: Schemas["Url"];
  }>;
  readonly InboxSummary: Readonly<{
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly id: Schemas["Identifier"];
    readonly name: string;
    readonly revoked: boolean;
  }>;
  readonly InboxPage: Readonly<{
    readonly items: readonly Schemas["InboxSummary"][];
    readonly nextCursor: Schemas["Cursor"] | null;
  }>;
  readonly InboxMetadata: Readonly<{
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly maxBytes: number;
    readonly maxFiles: number;
    readonly name: string;
    readonly uploadAvailable: boolean;
  }>;
  readonly RetentionPolicy: Readonly<{
    readonly branchGlob: string | null;
    readonly keepLatest: number;
    readonly pathGlob: string | null;
  }>;
  readonly ClearRetentionResult: Readonly<{ readonly cleared: true }>;
  readonly WebYardSummary: Readonly<{
    readonly currentDeployId: Schemas["Identifier"] | null;
    readonly hostLabel: string;
    readonly id: Schemas["Identifier"];
    readonly name: Schemas["Slug"];
    readonly projectId: Schemas["Identifier"];
    readonly status: "active" | "suspended";
    readonly url: Schemas["Url"];
    readonly workspaceId: Schemas["Identifier"];
  }>;
  readonly WebYardPage: Readonly<{
    readonly items: readonly Schemas["WebYardSummary"][];
    readonly nextCursor: Schemas["Cursor"] | null;
  }>;
  readonly YardDeploySummary: Readonly<{
    readonly cleanUrls: boolean;
    readonly clientDeployId: Schemas["Identifier"];
    readonly createdAt: Schemas["UnixMilliseconds"];
    readonly deploymentUrl: Schemas["Url"];
    readonly fileCount: number;
    readonly finalisedAt: Schemas["UnixMilliseconds"] | null;
    readonly id: Schemas["Identifier"];
    readonly isCurrent: boolean;
    readonly spa: boolean;
    readonly status: "uploading" | "finalising" | "live" | "failed" | "superseded" | "pruned";
    readonly totalBytes: number;
  }>;
  readonly YardDeployPage: Readonly<{
    readonly items: readonly Schemas["YardDeploySummary"][];
    readonly nextCursor: Schemas["Cursor"] | null;
  }>;
  readonly StartWebYardDeployResult: Readonly<{
    readonly deployId: Schemas["Identifier"];
    readonly deploymentUrl: Schemas["Url"];
    readonly hostLabel: string;
    readonly manifestRoot: string;
    readonly status: "uploading";
    readonly url: Schemas["Url"];
    readonly yardId: Schemas["Identifier"];
    readonly yardName: Schemas["Slug"];
  }>;
  readonly YardDeploymentResult: Readonly<{
    readonly deployId: Schemas["Identifier"];
    readonly deploymentUrl: Schemas["Url"];
    readonly status: "live" | "superseded";
    readonly url: Schemas["Url"];
  }>;
  readonly AuditEvent: Readonly<{
    readonly action: string;
    readonly actor: string;
    readonly createdAt: Schemas["IsoTimestamp"];
    readonly id: Schemas["Identifier"];
    readonly metadata?: Readonly<Record<string, string | number | boolean | null>>;
    readonly requestId: string;
    readonly targetType: string;
  }>;
  readonly AuditPage: Readonly<{
    readonly items: readonly Schemas["AuditEvent"][];
    readonly nextCursor: Schemas["Cursor"] | null;
  }>;
  readonly MemberSummary: Readonly<{
    readonly displayName: string | null;
    readonly email: string;
    readonly joinedAt: Schemas["UnixMilliseconds"];
    readonly role: "owner" | "admin" | "member";
    readonly userId: Schemas["Identifier"];
  }>;
  readonly SeatState: Readonly<{
    readonly active: number;
    readonly limit: number | null;
    readonly reserved: number;
    readonly used: number;
  }>;
  readonly MemberList: Readonly<{
    readonly members: readonly Schemas["MemberSummary"][];
    readonly seats: Schemas["SeatState"];
  }>;
  readonly InviteSummary: Readonly<{
    readonly createdAt: Schemas["UnixMilliseconds"];
    readonly email: string;
    readonly expiresAt: Schemas["UnixMilliseconds"];
    readonly id: Schemas["Identifier"];
    readonly role: "owner" | "admin" | "member";
    readonly status: string;
  }>;
  readonly InviteList: readonly Schemas["InviteSummary"][];
  readonly CreateInviteResult: Readonly<{
    readonly expiresAt: Schemas["UnixMilliseconds"];
    readonly id: Schemas["Identifier"];
    readonly inviteUrl: Schemas["Url"];
  }>;
  readonly ApiTokenSummary: Readonly<{
    readonly createdAt: Schemas["UnixMilliseconds"];
    readonly expiresAt: Schemas["UnixMilliseconds"];
    readonly id: Schemas["Identifier"];
    readonly lastUsedAt: Schemas["UnixMilliseconds"] | null;
    readonly name: string;
    readonly projectId?: Schemas["Identifier"] | null;
    readonly scopes: readonly string[];
    readonly status: string;
    readonly tokenPrefix: string;
    readonly workspaceId?: Schemas["Identifier"] | null;
  }>;
  readonly ApiTokenList: readonly Schemas["ApiTokenSummary"][];
  readonly CreateApiTokenResult: Readonly<{
    readonly expiresAt: Schemas["UnixMilliseconds"];
    readonly id: Schemas["Identifier"];
    readonly name: string;
    readonly projectId?: Schemas["Identifier"];
    readonly rawToken: string;
    readonly scopes: readonly string[];
    readonly workspaceId?: Schemas["Identifier"];
  }>;
  readonly CiTrustSummary: Readonly<{
    readonly allowedActions: readonly string[];
    readonly allowedRefGlob: string;
    readonly createdAt: Schemas["UnixMilliseconds"];
    readonly environment: string | null;
    readonly id: Schemas["Identifier"];
    readonly projectId: Schemas["Identifier"] | null;
    readonly repository: string;
    readonly revokedAt: Schemas["UnixMilliseconds"] | null;
    readonly workflowPath: string;
    readonly workflowRef: string;
  }>;
  readonly CiTrustList: readonly Schemas["CiTrustSummary"][];
  readonly CliSessionSummary: Readonly<{
    readonly createdAt: Schemas["UnixMilliseconds"];
    readonly id: Schemas["Identifier"];
    readonly lastUsedAt: Schemas["UnixMilliseconds"] | null;
    readonly name: string;
    readonly platform: string;
    readonly version: string;
  }>;
  readonly CliSessionList: readonly Schemas["CliSessionSummary"][];
  readonly BillingSessionResult: Readonly<{ readonly url: Schemas["Url"] }>;
  readonly AccountExportRequestStatus: "queued" | "running";
  readonly AccountExportResult: Readonly<{
    readonly exportId: Schemas["Identifier"];
    readonly status: Schemas["AccountExportRequestStatus"];
  }>;
  readonly PrepareAccountDeletionResult: Readonly<{
    readonly confirmationToken: Schemas["CapabilityToken"];
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly recoveryToken: Schemas["CapabilityToken"];
  }>;
  readonly CompleteAccountDeletionResult: Readonly<{
    readonly jobId: Schemas["Identifier"];
    readonly status: "queued";
  }>;
  readonly AccountDeletionRetryStatus: "running";
  readonly CreateOneTimeSecretResult: Readonly<{
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly version: "aes-gcm-256-v1";
  }>;
  readonly RedeemOneTimeSecretResult: Readonly<{
    readonly ciphertext: string;
    readonly expiresAt: Schemas["IsoTimestamp"];
    readonly initializationVector: string;
    readonly version: "aes-gcm-256-v1";
  }>;
  readonly RevocationResult: Readonly<{
    readonly status: "revoked" | "invalid" | "already_revoked";
  }>;
  readonly ApiError: Readonly<{ readonly code: string; readonly message: string }>;
  readonly ApiErrorEnvelope: Readonly<{
    readonly error: Schemas["ApiError"];
    readonly ok: false;
    readonly requestId: string;
  }>;
  readonly HealthSuccessEnvelope: Readonly<{
    readonly data: Schemas["HealthResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ExchangeBootstrapTokenRequest: Readonly<{
    readonly name: string;
    readonly platform: string;
    readonly token: Schemas["CapabilityToken"];
    readonly version: string;
  }>;
  readonly ExchangeBootstrapTokenSuccessEnvelope: Readonly<{
    readonly data: Schemas["ExchangeBootstrapTokenResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly StartDeviceLoginRequest: Readonly<{
    readonly name: string;
    readonly platform: string;
    readonly version: string;
  }>;
  readonly StartDeviceLoginResult: Schemas["DeviceStartResult"];
  readonly StartDeviceLoginSuccessEnvelope: Readonly<{
    readonly data: Schemas["StartDeviceLoginResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly PollDeviceLoginRequest: Readonly<{ readonly deviceCode: Schemas["CapabilityToken"] }>;
  readonly PollDeviceLoginResult: Schemas["DevicePollResult"];
  readonly PollDeviceLoginSuccessEnvelope: Readonly<{
    readonly data: Schemas["PollDeviceLoginResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RefreshCliSessionRequest: Readonly<{
    readonly refreshToken: Schemas["CapabilityToken"];
  }>;
  readonly RefreshCliSessionResult: Schemas["TokenPair"];
  readonly RefreshCliSessionSuccessEnvelope: Readonly<{
    readonly data: Schemas["RefreshCliSessionResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly LogoutCliSessionRequest: Readonly<Record<string, never>>;
  readonly LogoutCliSessionResult: Schemas["EmptyResult"];
  readonly LogoutCliSessionSuccessEnvelope: Readonly<{
    readonly data: Schemas["LogoutCliSessionResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly WhoAmISuccessEnvelope: Readonly<{
    readonly data: Schemas["WhoAmIResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ListWorkspacesQuery: Readonly<{ readonly cursor?: Schemas["Cursor"] }>;
  readonly ListWorkspacesResult: Schemas["WorkspacePage"];
  readonly ListWorkspacesSuccessEnvelope: Readonly<{
    readonly data: Schemas["ListWorkspacesResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CreateWorkspaceRequest: Readonly<{ readonly name: string }>;
  readonly CreateWorkspaceResult: Schemas["WorkspaceSummary"];
  readonly CreateWorkspaceSuccessEnvelope: Readonly<{
    readonly data: Schemas["CreateWorkspaceResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ListProjectsQuery: Readonly<{
    readonly cursor?: Schemas["Cursor"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly ListProjectsResult: Schemas["ProjectPage"];
  readonly ListProjectsSuccessEnvelope: Readonly<{
    readonly data: Schemas["ListProjectsResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CreateProjectRequest: Readonly<{
    readonly name: string;
    readonly workspace: Schemas["Slug"];
  }>;
  readonly CreateProjectResult: Schemas["ProjectSummary"];
  readonly CreateProjectSuccessEnvelope: Readonly<{
    readonly data: Schemas["CreateProjectResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CiAction: "upload" | "share" | "download" | "yard:manage";
  readonly ExchangeGitHubOidcRequest: Readonly<{
    readonly actions: readonly Schemas["CiAction"][];
    readonly project: Schemas["Slug"];
    readonly workspace?: Schemas["Slug"];
  }>;
  readonly ExchangeGitHubOidcResult: Schemas["MachineTokenResult"];
  readonly ExchangeGitHubOidcSuccessEnvelope: Readonly<{
    readonly data: Schemas["ExchangeGitHubOidcResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RequestUploadRequest: Readonly<{
    readonly checksumSha256: string;
    readonly contentType: string;
    readonly filename: string;
    readonly gitBranch?: string;
    readonly gitCommit?: string;
    readonly gitRepository?: string;
    readonly path: string;
    readonly project: Schemas["Slug"];
    readonly sizeBytes: number;
    readonly workspace: Schemas["Slug"];
  }>;
  readonly RequestUploadSuccessEnvelope: Readonly<{
    readonly data: Schemas["RequestUploadResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RequestUploadPartsRequest: Readonly<{
    readonly partNumbers: readonly number[];
    readonly uploadId: Schemas["Identifier"];
  }>;
  readonly RequestUploadPartsSuccessEnvelope: Readonly<{
    readonly data: Schemas["RequestUploadPartsResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CompleteUploadRequest: Readonly<{
    readonly parts: readonly Readonly<{ readonly etag: string; readonly partNumber: number }>[];
    readonly uploadId: Schemas["Identifier"];
  }>;
  readonly CompleteUploadSuccessEnvelope: Readonly<{
    readonly data: Schemas["CompleteUploadResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly AbortUploadRequest: Readonly<{ readonly uploadId: Schemas["Identifier"] }>;
  readonly AbortUploadResult: Schemas["EmptyResult"];
  readonly AbortUploadSuccessEnvelope: Readonly<{
    readonly data: Schemas["AbortUploadResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly GetUploadStatusQuery: Readonly<{ readonly uploadId: Schemas["Identifier"] }>;
  readonly GetUploadStatusResult: Schemas["UploadStatusResult"];
  readonly GetUploadStatusSuccessEnvelope: Readonly<{
    readonly data: Schemas["GetUploadStatusResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ListObjectsQuery: Readonly<{
    readonly cursor?: Schemas["Cursor"];
    readonly prefix?: string;
    readonly project: Schemas["Slug"];
    readonly versions: boolean;
    readonly workspace: Schemas["Slug"];
  }>;
  readonly ListObjectsResult: Schemas["ObjectPage"];
  readonly ListObjectsSuccessEnvelope: Readonly<{
    readonly data: Schemas["ListObjectsResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly DeleteObjectRequest: Readonly<{ readonly uri: Schemas["BlobyardUri"] }>;
  readonly DeleteObjectSuccessEnvelope: Readonly<{
    readonly data: Schemas["DeleteObjectResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RequestDownloadRequest: Readonly<{ readonly uri: Schemas["BlobyardUri"] }>;
  readonly RequestDownloadResult: Schemas["DownloadResult"];
  readonly RequestDownloadSuccessEnvelope: Readonly<{
    readonly data: Schemas["RequestDownloadResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ListSharesQuery: Readonly<{ readonly workspace: Schemas["Slug"] }>;
  readonly ListSharesResult: Schemas["SharePage"];
  readonly ListSharesSuccessEnvelope: Readonly<{
    readonly data: Schemas["ListSharesResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CreateShareRequest: Readonly<{
    readonly expires: string | null;
    readonly notify: string | null;
    readonly target: Schemas["BlobyardUri"];
  }>;
  readonly CreateShareSuccessEnvelope: Readonly<{
    readonly data: Schemas["CreateShareResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ResolveShareQuery: Readonly<{ readonly token: Schemas["CapabilityToken"] }>;
  readonly ResolveShareResult: Schemas["ShareMetadata"];
  readonly ResolveShareSuccessEnvelope: Readonly<{
    readonly data: Schemas["ResolveShareResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly DownloadShareRequest: Readonly<{ readonly token: Schemas["CapabilityToken"] }>;
  readonly DownloadShareResult: Schemas["DownloadResult"];
  readonly DownloadShareSuccessEnvelope: Readonly<{
    readonly data: Schemas["DownloadShareResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RevokeShareRequest: Readonly<{ readonly shareId: Schemas["Identifier"] }>;
  readonly RevokeShareResult: Schemas["EmptyResult"];
  readonly RevokeShareSuccessEnvelope: Readonly<{
    readonly data: Schemas["RevokeShareResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ListPreviewsQuery: Readonly<{
    readonly cursor?: Schemas["Cursor"];
    readonly project: Schemas["Slug"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly ListPreviewsResult: Schemas["PreviewPage"];
  readonly ListPreviewsSuccessEnvelope: Readonly<{
    readonly data: Schemas["ListPreviewsResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CreatePreviewRequest: Readonly<{
    readonly expires: string | null;
    readonly manifestId: Schemas["Identifier"];
    readonly project: Schemas["Slug"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly CreatePreviewSuccessEnvelope: Readonly<{
    readonly data: Schemas["CreatePreviewResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RevokePreviewRequest: Readonly<{ readonly previewId: Schemas["Identifier"] }>;
  readonly RevokePreviewResult: Schemas["EmptyResult"];
  readonly RevokePreviewSuccessEnvelope: Readonly<{
    readonly data: Schemas["RevokePreviewResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ListWebYardsQuery: Readonly<{
    readonly project: Schemas["Slug"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly ListWebYardsResult: Schemas["WebYardPage"];
  readonly ListWebYardsSuccessEnvelope: Readonly<{
    readonly data: Schemas["ListWebYardsResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ListWebYardDeploysQuery: Readonly<{ readonly yardId: Schemas["Identifier"] }>;
  readonly ListWebYardDeploysResult: Schemas["YardDeployPage"];
  readonly ListWebYardDeploysSuccessEnvelope: Readonly<{
    readonly data: Schemas["ListWebYardDeploysResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly StartWebYardDeployRequest: Readonly<{
    readonly cleanUrls: boolean;
    readonly clientDeployId: Schemas["Identifier"];
    readonly name: Schemas["Slug"];
    readonly project: Schemas["Slug"];
    readonly public: boolean;
    readonly spa: boolean;
    readonly workspace: Schemas["Slug"];
  }>;
  readonly StartWebYardDeploySuccessEnvelope: Readonly<{
    readonly data: Schemas["StartWebYardDeployResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly FinaliseWebYardDeployRequest: Readonly<{ readonly deployId: Schemas["Identifier"] }>;
  readonly FinaliseWebYardDeployResult: Schemas["YardDeploymentResult"];
  readonly FinaliseWebYardDeploySuccessEnvelope: Readonly<{
    readonly data: Schemas["FinaliseWebYardDeployResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly FailWebYardDeployRequest: Readonly<{
    readonly deployId: Schemas["Identifier"];
    readonly failureCode: string;
    readonly failureMessage: string;
  }>;
  readonly FailWebYardDeployResult: Schemas["EmptyResult"];
  readonly FailWebYardDeploySuccessEnvelope: Readonly<{
    readonly data: Schemas["FailWebYardDeployResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RollbackWebYardRequest: Readonly<{
    readonly deployId?: Schemas["Identifier"];
    readonly yardId: Schemas["Identifier"];
  }>;
  readonly RollbackWebYardResult: Schemas["YardDeploymentResult"];
  readonly RollbackWebYardSuccessEnvelope: Readonly<{
    readonly data: Schemas["RollbackWebYardResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly DeleteWebYardRequest: Readonly<{ readonly yardId: Schemas["Identifier"] }>;
  readonly DeleteWebYardResult: Schemas["EmptyResult"];
  readonly DeleteWebYardSuccessEnvelope: Readonly<{
    readonly data: Schemas["DeleteWebYardResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ListInboxesQuery: Readonly<{
    readonly cursor?: Schemas["Cursor"];
    readonly project: Schemas["Slug"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly ListInboxesResult: Schemas["InboxPage"];
  readonly ListInboxesSuccessEnvelope: Readonly<{
    readonly data: Schemas["ListInboxesResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CreateInboxRequest: Readonly<{
    readonly expires: string | null;
    readonly name: string;
    readonly project: Schemas["Slug"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly CreateInboxSuccessEnvelope: Readonly<{
    readonly data: Schemas["CreateInboxResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ResolveInboxQuery: Readonly<{ readonly token: Schemas["CapabilityToken"] }>;
  readonly ResolveInboxResult: Schemas["InboxMetadata"];
  readonly ResolveInboxSuccessEnvelope: Readonly<{
    readonly data: Schemas["ResolveInboxResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RevokeInboxRequest: Readonly<{ readonly inboxId: Schemas["Identifier"] }>;
  readonly RevokeInboxResult: Schemas["EmptyResult"];
  readonly RevokeInboxSuccessEnvelope: Readonly<{
    readonly data: Schemas["RevokeInboxResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly GetRetentionQuery: Readonly<{
    readonly project: Schemas["Slug"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly GetRetentionResult: Schemas["RetentionPolicy"];
  readonly GetRetentionSuccessEnvelope: Readonly<{
    readonly data: Schemas["GetRetentionResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly SetRetentionRequest: Readonly<{
    readonly branch?: string;
    readonly keepLatest: number;
    readonly path?: string;
    readonly project: Schemas["Slug"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly SetRetentionResult: Schemas["RetentionPolicy"];
  readonly SetRetentionSuccessEnvelope: Readonly<{
    readonly data: Schemas["SetRetentionResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ClearRetentionRequest: Readonly<{
    readonly project: Schemas["Slug"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly ClearRetentionSuccessEnvelope: Readonly<{
    readonly data: Schemas["ClearRetentionResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ListAuditEventsQuery: Readonly<{
    readonly cursor?: Schemas["Cursor"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly ListAuditEventsResult: Schemas["AuditPage"];
  readonly ListAuditEventsSuccessEnvelope: Readonly<{
    readonly data: Schemas["ListAuditEventsResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ListMembersQuery: Readonly<{ readonly workspace: Schemas["Slug"] }>;
  readonly ListMembersResult: Schemas["MemberList"];
  readonly ListMembersSuccessEnvelope: Readonly<{
    readonly data: Schemas["ListMembersResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ListInvitesQuery: Readonly<{ readonly workspace: Schemas["Slug"] }>;
  readonly ListInvitesResult: Schemas["InviteList"];
  readonly ListInvitesSuccessEnvelope: Readonly<{
    readonly data: Schemas["ListInvitesResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CreateInviteRequest: Readonly<{
    readonly email: string;
    readonly role: "owner" | "admin" | "member";
    readonly workspace: Schemas["Slug"];
  }>;
  readonly CreateInviteSuccessEnvelope: Readonly<{
    readonly data: Schemas["CreateInviteResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RevokeInviteRequest: Readonly<{
    readonly inviteId: Schemas["Identifier"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly RevokeInviteResult: Schemas["EmptyResult"];
  readonly RevokeInviteSuccessEnvelope: Readonly<{
    readonly data: Schemas["RevokeInviteResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly UpdateMemberRoleRequest: Readonly<{
    readonly role: "owner" | "admin" | "member";
    readonly targetUserId: Schemas["Identifier"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly UpdateMemberRoleResult: Schemas["EmptyResult"];
  readonly UpdateMemberRoleSuccessEnvelope: Readonly<{
    readonly data: Schemas["UpdateMemberRoleResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RemoveMemberRequest: Readonly<{
    readonly targetUserId: Schemas["Identifier"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly RemoveMemberResult: Schemas["EmptyResult"];
  readonly RemoveMemberSuccessEnvelope: Readonly<{
    readonly data: Schemas["RemoveMemberResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ListApiTokensResult: Schemas["ApiTokenList"];
  readonly ListApiTokensSuccessEnvelope: Readonly<{
    readonly data: Schemas["ListApiTokensResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CreateApiTokenRequest: Readonly<{
    readonly expiresInDays: 7 | 30 | 90;
    readonly name: string;
    readonly project?: Schemas["Slug"];
    readonly scopes: readonly string[];
    readonly workspace?: Schemas["Slug"];
  }>;
  readonly CreateApiTokenSuccessEnvelope: Readonly<{
    readonly data: Schemas["CreateApiTokenResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RevokeApiTokenRequest: Readonly<{ readonly tokenId: Schemas["Identifier"] }>;
  readonly RevokeApiTokenResult: Schemas["RevocationResult"];
  readonly RevokeApiTokenSuccessEnvelope: Readonly<{
    readonly data: Schemas["RevokeApiTokenResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ListCiTrustsQuery: Readonly<{ readonly workspace: Schemas["Slug"] }>;
  readonly ListCiTrustsResult: Schemas["CiTrustList"];
  readonly ListCiTrustsSuccessEnvelope: Readonly<{
    readonly data: Schemas["ListCiTrustsResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CreateCiTrustRequest: Readonly<{
    readonly allowedActions: readonly string[];
    readonly allowedRefGlob: string;
    readonly environment?: string;
    readonly project?: Schemas["Slug"];
    readonly repository: string;
    readonly workflowPath: string;
    readonly workflowRef: string;
    readonly workspace: Schemas["Slug"];
  }>;
  readonly CreateCiTrustResult: Schemas["CiTrustSummary"];
  readonly CreateCiTrustSuccessEnvelope: Readonly<{
    readonly data: Schemas["CreateCiTrustResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RevokeCiTrustRequest: Readonly<{ readonly trustId: Schemas["Identifier"] }>;
  readonly RevokeCiTrustResult: "revoked" | "already_revoked";
  readonly RevokeCiTrustSuccessEnvelope: Readonly<{
    readonly data: Schemas["RevokeCiTrustResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly ListCliSessionsResult: Schemas["CliSessionList"];
  readonly ListCliSessionsSuccessEnvelope: Readonly<{
    readonly data: Schemas["ListCliSessionsResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RevokeCliSessionRequest: Readonly<{ readonly sessionId: Schemas["Identifier"] }>;
  readonly RevokeCliSessionResult: Schemas["RevocationResult"];
  readonly RevokeCliSessionSuccessEnvelope: Readonly<{
    readonly data: Schemas["RevokeCliSessionResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CreateOneTimeSecretRequest: Readonly<{
    readonly ciphertext: string;
    readonly expiresIn: "1h" | "24h" | "7d";
    readonly initializationVector: string;
    readonly tokenHash: string;
    readonly version: "aes-gcm-256-v1";
  }>;
  readonly CreateOneTimeSecretSuccessEnvelope: Readonly<{
    readonly data: Schemas["CreateOneTimeSecretResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RedeemOneTimeSecretRequest: Readonly<{
    readonly tokenHash: string;
    readonly version: "aes-gcm-256-v1";
  }>;
  readonly RedeemOneTimeSecretSuccessEnvelope: Readonly<{
    readonly data: Schemas["RedeemOneTimeSecretResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RenameWorkspaceRequest: Readonly<{
    readonly name: string;
    readonly workspace: Schemas["Slug"];
  }>;
  readonly RenameWorkspaceResult: Schemas["WorkspaceSummary"];
  readonly RenameWorkspaceSuccessEnvelope: Readonly<{
    readonly data: Schemas["RenameWorkspaceResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CreateBillingCheckoutRequest:
    | Readonly<{ readonly plan: "solo" }>
    | Readonly<{ readonly plan: "team"; readonly seats: number }>;
  readonly CreateBillingCheckoutResult: Schemas["BillingSessionResult"];
  readonly CreateBillingCheckoutSuccessEnvelope: Readonly<{
    readonly data: Schemas["CreateBillingCheckoutResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CreateBillingPortalRequest: Readonly<Record<string, never>>;
  readonly CreateBillingPortalResult: Schemas["BillingSessionResult"];
  readonly CreateBillingPortalSuccessEnvelope: Readonly<{
    readonly data: Schemas["CreateBillingPortalResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly BillingSubscriptionStatus:
    | "incomplete"
    | "incomplete_expired"
    | "trialing"
    | "active"
    | "past_due"
    | "canceled"
    | "unpaid"
    | "paused";
  readonly BillingProjection: Readonly<{
    readonly canManageSubscription: boolean;
    readonly canStartCheckout: boolean;
    readonly customerConfigured: boolean;
    readonly limits: Schemas["BillingLimits"];
    readonly plan: "free" | "solo" | "team" | "byo";
    readonly status: "active" | "restricted" | "suspended";
    readonly storageBlockMaximum: number;
    readonly subscription: Schemas["BillingSubscription"] | null;
    readonly storageSubscription: Schemas["StorageSubscription"] | null;
    readonly usage: Schemas["BillingUsage"];
  }>;
  readonly BillingLimits: Readonly<{
    readonly members: number | null;
    readonly projects: number | null;
    readonly storageBytes: number | null;
    readonly workspaces: number | null;
  }>;
  readonly BillingSubscription: Readonly<{
    readonly cancelAtPeriodEnd: boolean;
    readonly currentPeriodEnd: Schemas["UnixMilliseconds"];
    readonly plan: "solo" | "team";
    readonly seats: number;
    readonly status: Schemas["BillingSubscriptionStatus"];
  }>;
  readonly StorageSubscription: Readonly<{
    readonly cancelAtPeriodEnd: boolean;
    readonly currentPeriodEnd: Schemas["UnixMilliseconds"];
    readonly status: Schemas["BillingSubscriptionStatus"];
    readonly storageBlockCount: number;
  }>;
  readonly BillingUsage: Readonly<{
    readonly members: number;
    readonly objectCount: number;
    readonly projects: number;
    readonly readyBytes: number;
    readonly reservedUploadBytes: number;
    readonly versionCount: number;
    readonly workspaces: number;
  }>;
  readonly GetBillingResult: Schemas["BillingProjection"];
  readonly GetBillingSuccessEnvelope: Readonly<{
    readonly data: Schemas["GetBillingResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CreateStorageCheckoutRequest: Readonly<{ readonly storageBlockCount: number }>;
  readonly CreateStorageCheckoutResult: Schemas["BillingSessionResult"];
  readonly CreateStorageCheckoutSuccessEnvelope: Readonly<{
    readonly data: Schemas["CreateStorageCheckoutResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CreateStorageUpdateRequest: Schemas["CreateStorageCheckoutRequest"];
  readonly CreateStorageUpdateResult: Schemas["BillingSessionResult"];
  readonly CreateStorageUpdateSuccessEnvelope: Readonly<{
    readonly data: Schemas["CreateStorageUpdateResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CreateBillingSubscriptionUpdateRequest: Schemas["CreateBillingCheckoutRequest"];
  readonly CreateBillingSubscriptionUpdateResult: Schemas["BillingSessionResult"];
  readonly CreateBillingSubscriptionUpdateSuccessEnvelope: Readonly<{
    readonly data: Schemas["CreateBillingSubscriptionUpdateResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly AccountExportState: Readonly<{
    readonly artifactCount: number;
    readonly errorCode: string | null;
    readonly expiresAt: Schemas["UnixMilliseconds"];
    readonly id: Schemas["Identifier"];
    readonly status: "queued" | "running" | "ready" | "failed" | "expired";
  }>;
  readonly GetAccountExportResult: Schemas["AccountExportState"] | null;
  readonly GetAccountExportSuccessEnvelope: Readonly<{
    readonly data: Schemas["GetAccountExportResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly DownloadAccountExportRequest: Readonly<{
    readonly exportId: string;
    readonly partNumber: number;
  }>;
  readonly DownloadAccountExportResult: Readonly<{
    readonly downloadUrl: Schemas["Url"];
    readonly expiresAt: Schemas["UnixMilliseconds"];
  }>;
  readonly DownloadAccountExportSuccessEnvelope: Readonly<{
    readonly data: Schemas["DownloadAccountExportResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly AccountDeletionState: Readonly<{
    readonly errorCode: string | null;
    readonly requestedAt: Schemas["UnixMilliseconds"];
    readonly stage:
      | "cancel_subscription"
      | "delete_object_storage"
      | "delete_preview_storage"
      | "delete_export_storage"
      | "revoke_credentials"
      | "delete_versions"
      | "delete_previews"
      | "delete_inboxes"
      | "delete_projects"
      | "delete_workspace_security"
      | "delete_workspaces"
      | "delete_external_memberships"
      | "delete_account_records"
      | "minimize_audit"
      | "await_identity";
    readonly status:
      | "queued"
      | "running"
      | "failed"
      | "awaiting_identity_deletion"
      | "identity_deleting"
      | "complete";
    readonly updatedAt: Schemas["UnixMilliseconds"];
  }>;
  readonly GetAccountDeletionResult: Schemas["AccountDeletionState"] | null;
  readonly GetAccountDeletionSuccessEnvelope: Readonly<{
    readonly data: Schemas["GetAccountDeletionResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RetryAccountDeletionRequest: Readonly<{ readonly confirmation: "DELETE MY ACCOUNT" }>;
  readonly RetryAccountDeletionResult: Readonly<{
    readonly jobId: Schemas["Identifier"];
    readonly status: Schemas["AccountDeletionRetryStatus"];
  }>;
  readonly RetryAccountDeletionSuccessEnvelope: Readonly<{
    readonly data: Schemas["RetryAccountDeletionResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RetentionRun: Readonly<{
    readonly candidateCount: number;
    readonly completedAt: Schemas["UnixMilliseconds"] | null;
    readonly deletedCount: number;
    readonly errorSummary: string | null;
    readonly startedAt: Schemas["UnixMilliseconds"];
    readonly status: "complete" | "failed" | "running";
  }>;
  readonly RetentionOverview: Readonly<{
    readonly lastRun: Schemas["RetentionRun"] | null;
    readonly policy: Schemas["RetentionPolicy"] | null;
  }>;
  readonly GetRetentionOverviewResult: Schemas["RetentionOverview"];
  readonly GetRetentionOverviewSuccessEnvelope: Readonly<{
    readonly data: Schemas["GetRetentionOverviewResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly RequestAccountExportRequest: Readonly<Record<string, never>>;
  readonly RequestAccountExportResult: Schemas["AccountExportResult"];
  readonly RequestAccountExportSuccessEnvelope: Readonly<{
    readonly data: Schemas["RequestAccountExportResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly PrepareAccountDeletionRequest: Readonly<Record<string, never>>;
  readonly PrepareAccountDeletionSuccessEnvelope: Readonly<{
    readonly data: Schemas["PrepareAccountDeletionResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
  readonly CompleteAccountDeletionRequest: Readonly<{ readonly confirmationToken: string }>;
  readonly CompleteAccountDeletionSuccessEnvelope: Readonly<{
    readonly data: Schemas["CompleteAccountDeletionResult"];
    readonly ok: true;
    readonly requestId: string;
  }>;
}
export type AbortUploadInput = Readonly<{
  readonly body: Schemas["AbortUploadRequest"];
  readonly signal?: AbortSignal;
}>;
export type ClearRetentionInput = Readonly<{
  readonly query: Readonly<{
    readonly project: Schemas["Slug"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly signal?: AbortSignal;
}>;
export type CompleteAccountDeletionInput = Readonly<{
  readonly body: Schemas["CompleteAccountDeletionRequest"];
  readonly idempotencyKey?: string;
  readonly signal?: AbortSignal;
}>;
export type CompleteUploadInput = Readonly<{
  readonly body: Schemas["CompleteUploadRequest"];
  readonly signal?: AbortSignal;
}>;
export type CreateApiTokenInput = Readonly<{
  readonly body: Schemas["CreateApiTokenRequest"];
  readonly signal?: AbortSignal;
}>;
export type CreateBillingCheckoutInput = Readonly<{
  readonly body: Schemas["CreateBillingCheckoutRequest"];
  readonly idempotencyKey?: string;
  readonly signal?: AbortSignal;
}>;
export type CreateBillingPortalInput = Readonly<{
  readonly body: Schemas["CreateBillingPortalRequest"];
  readonly idempotencyKey?: string;
  readonly signal?: AbortSignal;
}>;
export type CreateBillingSubscriptionUpdateInput = Readonly<{
  readonly body: Schemas["CreateBillingSubscriptionUpdateRequest"];
  readonly signal?: AbortSignal;
}>;
export type CreateCiTrustInput = Readonly<{
  readonly body: Schemas["CreateCiTrustRequest"];
  readonly signal?: AbortSignal;
}>;
export type CreateInboxInput = Readonly<{
  readonly body: Schemas["CreateInboxRequest"];
  readonly signal?: AbortSignal;
}>;
export type CreateInviteInput = Readonly<{
  readonly body: Schemas["CreateInviteRequest"];
  readonly signal?: AbortSignal;
}>;
export type CreateOneTimeSecretInput = Readonly<{
  readonly body: Schemas["CreateOneTimeSecretRequest"];
  readonly signal?: AbortSignal;
}>;
export type CreatePreviewInput = Readonly<{
  readonly body: Schemas["CreatePreviewRequest"];
  readonly signal?: AbortSignal;
}>;
export type CreateProjectInput = Readonly<{
  readonly body: Schemas["CreateProjectRequest"];
  readonly signal?: AbortSignal;
}>;
export type CreateShareInput = Readonly<{
  readonly body: Schemas["CreateShareRequest"];
  readonly signal?: AbortSignal;
}>;
export type CreateStorageCheckoutInput = Readonly<{
  readonly body: Schemas["CreateStorageCheckoutRequest"];
  readonly signal?: AbortSignal;
}>;
export type CreateStorageUpdateInput = Readonly<{
  readonly body: Schemas["CreateStorageUpdateRequest"];
  readonly signal?: AbortSignal;
}>;
export type CreateWorkspaceInput = Readonly<{
  readonly body: Schemas["CreateWorkspaceRequest"];
  readonly signal?: AbortSignal;
}>;
export type DeleteObjectInput = Readonly<{
  readonly body: Schemas["DeleteObjectRequest"];
  readonly signal?: AbortSignal;
}>;
export type DeleteWebYardInput = Readonly<{
  readonly body: Schemas["DeleteWebYardRequest"];
  readonly signal?: AbortSignal;
}>;
export type DownloadAccountExportInput = Readonly<{
  readonly body: Schemas["DownloadAccountExportRequest"];
  readonly signal?: AbortSignal;
}>;
export type DownloadShareInput = Readonly<{
  readonly body: Schemas["DownloadShareRequest"];
  readonly signal?: AbortSignal;
}>;
export type ExchangeBootstrapTokenInput = Readonly<{
  readonly body: Schemas["ExchangeBootstrapTokenRequest"];
  readonly signal?: AbortSignal;
}>;
export type ExchangeGitHubOidcInput = Readonly<{
  readonly body: Schemas["ExchangeGitHubOidcRequest"];
  readonly signal?: AbortSignal;
}>;
export type FailWebYardDeployInput = Readonly<{
  readonly body: Schemas["FailWebYardDeployRequest"];
  readonly signal?: AbortSignal;
}>;
export type FinaliseWebYardDeployInput = Readonly<{
  readonly body: Schemas["FinaliseWebYardDeployRequest"];
  readonly signal?: AbortSignal;
}>;
export type GetAccountDeletionInput = Readonly<{ readonly signal?: AbortSignal }>;
export type GetAccountExportInput = Readonly<{ readonly signal?: AbortSignal }>;
export type GetBillingInput = Readonly<{ readonly signal?: AbortSignal }>;
export type GetRetentionInput = Readonly<{
  readonly query: Readonly<{
    readonly project: Schemas["Slug"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly signal?: AbortSignal;
}>;
export type GetRetentionOverviewInput = Readonly<{
  readonly query: Readonly<{
    readonly project: Schemas["Slug"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly signal?: AbortSignal;
}>;
export type GetUploadStatusInput = Readonly<{
  readonly query: Readonly<{ readonly uploadId: Schemas["Identifier"] }>;
  readonly signal?: AbortSignal;
}>;
export type HealthInput = Readonly<{ readonly signal?: AbortSignal }>;
export type ListApiTokensInput = Readonly<{ readonly signal?: AbortSignal }>;
export type ListAuditEventsInput = Readonly<{
  readonly query: Readonly<{
    readonly cursor?: Schemas["Cursor"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly signal?: AbortSignal;
}>;
export type ListCiTrustsInput = Readonly<{
  readonly query: Readonly<{ readonly workspace: Schemas["Slug"] }>;
  readonly signal?: AbortSignal;
}>;
export type ListCliSessionsInput = Readonly<{ readonly signal?: AbortSignal }>;
export type ListInboxesInput = Readonly<{
  readonly query: Readonly<{
    readonly cursor?: Schemas["Cursor"];
    readonly project: Schemas["Slug"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly signal?: AbortSignal;
}>;
export type ListInvitesInput = Readonly<{
  readonly query: Readonly<{ readonly workspace: Schemas["Slug"] }>;
  readonly signal?: AbortSignal;
}>;
export type ListMembersInput = Readonly<{
  readonly query: Readonly<{ readonly workspace: Schemas["Slug"] }>;
  readonly signal?: AbortSignal;
}>;
export type ListObjectsInput = Readonly<{
  readonly query: Readonly<{
    readonly cursor?: Schemas["Cursor"];
    readonly prefix?: string;
    readonly project: Schemas["Slug"];
    readonly versions: boolean;
    readonly workspace: Schemas["Slug"];
  }>;
  readonly signal?: AbortSignal;
}>;
export type ListPreviewsInput = Readonly<{
  readonly query: Readonly<{
    readonly project: Schemas["Slug"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly signal?: AbortSignal;
}>;
export type ListProjectsInput = Readonly<{
  readonly query: Readonly<{
    readonly cursor?: Schemas["Cursor"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly signal?: AbortSignal;
}>;
export type ListSharesInput = Readonly<{
  readonly query: Readonly<{ readonly workspace: Schemas["Slug"] }>;
  readonly signal?: AbortSignal;
}>;
export type ListWebYardDeploysInput = Readonly<{
  readonly query: Readonly<{ readonly yardId: Schemas["Identifier"] }>;
  readonly signal?: AbortSignal;
}>;
export type ListWebYardsInput = Readonly<{
  readonly query: Readonly<{
    readonly project: Schemas["Slug"];
    readonly workspace: Schemas["Slug"];
  }>;
  readonly signal?: AbortSignal;
}>;
export type ListWorkspacesInput = Readonly<{
  readonly query?: Readonly<{ readonly cursor?: Schemas["Cursor"] }>;
  readonly signal?: AbortSignal;
}>;
export type LogoutCliSessionInput = Readonly<{
  readonly body: Schemas["LogoutCliSessionRequest"];
  readonly signal?: AbortSignal;
}>;
export type PollDeviceLoginInput = Readonly<{
  readonly body: Schemas["PollDeviceLoginRequest"];
  readonly signal?: AbortSignal;
}>;
export type PrepareAccountDeletionInput = Readonly<{
  readonly body: Schemas["PrepareAccountDeletionRequest"];
  readonly idempotencyKey?: string;
  readonly signal?: AbortSignal;
}>;
export type RedeemOneTimeSecretInput = Readonly<{
  readonly body: Schemas["RedeemOneTimeSecretRequest"];
  readonly signal?: AbortSignal;
}>;
export type RefreshCliSessionInput = Readonly<{
  readonly body: Schemas["RefreshCliSessionRequest"];
  readonly signal?: AbortSignal;
}>;
export type RemoveMemberInput = Readonly<{
  readonly body: Schemas["RemoveMemberRequest"];
  readonly signal?: AbortSignal;
}>;
export type RenameWorkspaceInput = Readonly<{
  readonly body: Schemas["RenameWorkspaceRequest"];
  readonly signal?: AbortSignal;
}>;
export type RequestAccountExportInput = Readonly<{
  readonly body: Schemas["RequestAccountExportRequest"];
  readonly idempotencyKey?: string;
  readonly signal?: AbortSignal;
}>;
export type RequestDownloadInput = Readonly<{
  readonly body: Schemas["RequestDownloadRequest"];
  readonly signal?: AbortSignal;
}>;
export type RequestUploadInput = Readonly<{
  readonly body: Schemas["RequestUploadRequest"];
  readonly idempotencyKey: string;
  readonly signal?: AbortSignal;
}>;
export type RequestUploadPartsInput = Readonly<{
  readonly body: Schemas["RequestUploadPartsRequest"];
  readonly signal?: AbortSignal;
}>;
export type ResolveInboxInput = Readonly<{
  readonly query: Readonly<{ readonly token: Schemas["CapabilityToken"] }>;
  readonly signal?: AbortSignal;
}>;
export type ResolveShareInput = Readonly<{
  readonly query: Readonly<{ readonly token: Schemas["CapabilityToken"] }>;
  readonly signal?: AbortSignal;
}>;
export type RetryAccountDeletionInput = Readonly<{
  readonly body: Schemas["RetryAccountDeletionRequest"];
  readonly signal?: AbortSignal;
}>;
export type RevokeApiTokenInput = Readonly<{
  readonly body: Schemas["RevokeApiTokenRequest"];
  readonly signal?: AbortSignal;
}>;
export type RevokeCiTrustInput = Readonly<{
  readonly body: Schemas["RevokeCiTrustRequest"];
  readonly signal?: AbortSignal;
}>;
export type RevokeCliSessionInput = Readonly<{
  readonly body: Schemas["RevokeCliSessionRequest"];
  readonly signal?: AbortSignal;
}>;
export type RevokeInboxInput = Readonly<{
  readonly body: Schemas["RevokeInboxRequest"];
  readonly signal?: AbortSignal;
}>;
export type RevokeInviteInput = Readonly<{
  readonly body: Schemas["RevokeInviteRequest"];
  readonly signal?: AbortSignal;
}>;
export type RevokePreviewInput = Readonly<{
  readonly body: Schemas["RevokePreviewRequest"];
  readonly signal?: AbortSignal;
}>;
export type RevokeShareInput = Readonly<{
  readonly body: Schemas["RevokeShareRequest"];
  readonly signal?: AbortSignal;
}>;
export type RollbackWebYardInput = Readonly<{
  readonly body: Schemas["RollbackWebYardRequest"];
  readonly signal?: AbortSignal;
}>;
export type SetRetentionInput = Readonly<{
  readonly body: Schemas["SetRetentionRequest"];
  readonly signal?: AbortSignal;
}>;
export type StartDeviceLoginInput = Readonly<{
  readonly body: Schemas["StartDeviceLoginRequest"];
  readonly signal?: AbortSignal;
}>;
export type StartWebYardDeployInput = Readonly<{
  readonly body: Schemas["StartWebYardDeployRequest"];
  readonly signal?: AbortSignal;
}>;
export type UpdateMemberRoleInput = Readonly<{
  readonly body: Schemas["UpdateMemberRoleRequest"];
  readonly signal?: AbortSignal;
}>;
export type WhoAmIInput = Readonly<{ readonly signal?: AbortSignal }>;
export declare const operations: Readonly<{
  readonly abortUpload: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/uploads/abort";
    public: false;
    requiredCiActions: readonly ["upload"];
    requiredUserScopes: readonly ["object:write"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly clearRetention: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "DELETE";
    ownership: "core";
    path: "/retention";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["retention:manage"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly completeAccountDeletion: Readonly<{
    idempotency: true;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/account/deletion/complete";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["account:delete"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly completeUpload: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/uploads/complete";
    public: false;
    requiredCiActions: readonly ["upload"];
    requiredUserScopes: readonly ["object:write"];
    risk: "write";
    successStatus: 200;
  }>;
  readonly createApiToken: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/api-tokens";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["tokens:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly createBillingCheckout: Readonly<{
    idempotency: true;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/billing/checkout";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["billing:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly createBillingPortal: Readonly<{
    idempotency: true;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/billing/portal";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["billing:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly createBillingSubscriptionUpdate: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/billing/subscription/update";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["billing:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly createCiTrust: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/ci/trusts";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["ci:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly createInbox: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/inboxes";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["inbox:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly createInvite: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/members/invites";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["members:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly createOneTimeSecret: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/secrets";
    public: true;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly [];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly createPreview: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/previews";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["share:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly createProject: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/projects";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["project:write"];
    risk: "write";
    successStatus: 200;
  }>;
  readonly createShare: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/shares";
    public: false;
    requiredCiActions: readonly ["share"];
    requiredUserScopes: readonly ["share:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly createStorageCheckout: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/billing/storage/checkout";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["billing:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly createStorageUpdate: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/billing/storage/update";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["billing:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly createWorkspace: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/workspaces";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["project:write"];
    risk: "write";
    successStatus: 200;
  }>;
  readonly deleteObject: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "DELETE";
    ownership: "core";
    path: "/objects";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["object:write"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly deleteWebYard: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/yards/delete";
    public: false;
    requiredCiActions: readonly ["yard:manage"];
    requiredUserScopes: readonly ["yard:manage"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly downloadAccountExport: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/account/exports/download";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["account:export"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly downloadShare: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/shares/download";
    public: true;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly [];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly exchangeBootstrapToken: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/bootstrap/exchange";
    public: true;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly [];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly exchangeGitHubOidc: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/ci/github/oidc/exchange";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly [];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly failWebYardDeploy: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/yards/deploys/fail";
    public: false;
    requiredCiActions: readonly ["upload", "yard:manage"];
    requiredUserScopes: readonly ["yard:manage"];
    risk: "write";
    successStatus: 200;
  }>;
  readonly finaliseWebYardDeploy: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/yards/deploys/finalise";
    public: false;
    requiredCiActions: readonly ["upload", "yard:manage"];
    requiredUserScopes: readonly ["yard:manage"];
    risk: "write";
    successStatus: 200;
  }>;
  readonly getAccountDeletion: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "hosted-extension";
    path: "/account/deletion";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["account:delete"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly getAccountExport: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "hosted-extension";
    path: "/account/exports";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["account:export"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly getBilling: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "hosted-extension";
    path: "/billing";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["billing:manage"];
    risk: "read";
    successStatus: 200;
  }>;
  readonly getRetention: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/retention";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["retention:manage"];
    risk: "read";
    successStatus: 200;
  }>;
  readonly getRetentionOverview: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/retention/overview";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["retention:manage"];
    risk: "read";
    successStatus: 200;
  }>;
  readonly getUploadStatus: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/uploads/status";
    public: false;
    requiredCiActions: readonly ["upload"];
    requiredUserScopes: readonly ["object:write"];
    risk: "read";
    successStatus: 200;
  }>;
  readonly health: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/health";
    public: true;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly [];
    risk: "read";
    successStatus: 200;
  }>;
  readonly listApiTokens: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/api-tokens";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["tokens:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly listAuditEvents: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/audit";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["audit:read"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly listCiTrusts: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/ci/trusts";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["ci:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly listCliSessions: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/cli/sessions";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["sessions:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly listInboxes: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/inboxes";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["inbox:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly listInvites: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "hosted-extension";
    path: "/members/invites";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["members:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly listMembers: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "hosted-extension";
    path: "/members";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["workspace:read"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly listObjects: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/objects";
    public: false;
    requiredCiActions: readonly ["download"];
    requiredUserScopes: readonly ["object:read"];
    risk: "read";
    successStatus: 200;
  }>;
  readonly listPreviews: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/previews";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["share:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly listProjects: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/projects";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["project:read"];
    risk: "read";
    successStatus: 200;
  }>;
  readonly listShares: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/shares";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["share:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly listWebYardDeploys: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/yards/deploys";
    public: false;
    requiredCiActions: readonly ["yard:manage"];
    requiredUserScopes: readonly ["yard:read"];
    risk: "read";
    successStatus: 200;
  }>;
  readonly listWebYards: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/yards";
    public: false;
    requiredCiActions: readonly ["yard:manage"];
    requiredUserScopes: readonly ["yard:read"];
    risk: "read";
    successStatus: 200;
  }>;
  readonly listWorkspaces: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/workspaces";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["workspace:read"];
    risk: "read";
    successStatus: 200;
  }>;
  readonly logoutCliSession: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/cli/logout";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly [];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly pollDeviceLogin: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/cli/device/poll";
    public: true;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly [];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly prepareAccountDeletion: Readonly<{
    idempotency: true;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/account/deletion/prepare";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["account:delete"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly redeemOneTimeSecret: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/secrets/redeem";
    public: true;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly [];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly refreshCliSession: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/cli/token/refresh";
    public: true;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly [];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly removeMember: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/members/remove";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["members:manage"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly renameWorkspace: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/workspaces/rename";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["project:write"];
    risk: "write";
    successStatus: 200;
  }>;
  readonly requestAccountExport: Readonly<{
    idempotency: true;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/account/exports";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["account:export"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly requestDownload: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/downloads/request";
    public: false;
    requiredCiActions: readonly ["download"];
    requiredUserScopes: readonly ["object:read"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly requestUpload: Readonly<{
    idempotency: true;
    idempotencyRequired: true;
    method: "POST";
    ownership: "core";
    path: "/uploads/request";
    public: false;
    requiredCiActions: readonly ["upload"];
    requiredUserScopes: readonly ["object:write"];
    risk: "write";
    successStatus: 200;
  }>;
  readonly requestUploadParts: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/uploads/parts/request";
    public: false;
    requiredCiActions: readonly ["upload"];
    requiredUserScopes: readonly ["object:write"];
    risk: "write";
    successStatus: 200;
  }>;
  readonly resolveInbox: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/inboxes/resolve";
    public: true;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly [];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly resolveShare: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/shares/resolve";
    public: true;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly [];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly retryAccountDeletion: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/account/deletion/retry";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["account:delete"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly revokeApiToken: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/api-tokens/revoke";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["tokens:manage"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly revokeCiTrust: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/ci/trusts/revoke";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["ci:manage"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly revokeCliSession: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/cli/sessions/revoke";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["sessions:manage"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly revokeInbox: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/inboxes/revoke";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["inbox:manage"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly revokeInvite: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/members/invites/revoke";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["members:manage"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly revokePreview: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/previews/revoke";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["share:manage"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly revokeShare: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/shares/revoke";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["share:manage"];
    risk: "destructive";
    successStatus: 200;
  }>;
  readonly rollbackWebYard: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/yards/rollback";
    public: false;
    requiredCiActions: readonly ["yard:manage"];
    requiredUserScopes: readonly ["yard:manage"];
    risk: "write";
    successStatus: 200;
  }>;
  readonly setRetention: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "PUT";
    ownership: "core";
    path: "/retention";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["retention:manage"];
    risk: "write";
    successStatus: 200;
  }>;
  readonly startDeviceLogin: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/cli/device/start";
    public: true;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly [];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly startWebYardDeploy: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "core";
    path: "/yards/deploys/start";
    public: false;
    requiredCiActions: readonly ["upload", "yard:manage"];
    requiredUserScopes: readonly ["yard:manage"];
    risk: "write";
    successStatus: 200;
  }>;
  readonly updateMemberRole: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "POST";
    ownership: "hosted-extension";
    path: "/members/role";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly ["members:manage"];
    risk: "sensitive";
    successStatus: 200;
  }>;
  readonly whoAmI: Readonly<{
    idempotency: false;
    idempotencyRequired: false;
    method: "GET";
    ownership: "core";
    path: "/cli/whoami";
    public: false;
    requiredCiActions: readonly [];
    requiredUserScopes: readonly [];
    risk: "read";
    successStatus: 200;
  }>;
}>;
export type OperationId = keyof typeof operations;
export type RequiredOperationId =
  | "abortUpload"
  | "clearRetention"
  | "completeAccountDeletion"
  | "completeUpload"
  | "createApiToken"
  | "createBillingCheckout"
  | "createBillingPortal"
  | "createBillingSubscriptionUpdate"
  | "createCiTrust"
  | "createInbox"
  | "createInvite"
  | "createOneTimeSecret"
  | "createPreview"
  | "createProject"
  | "createShare"
  | "createStorageCheckout"
  | "createStorageUpdate"
  | "createWorkspace"
  | "deleteObject"
  | "deleteWebYard"
  | "downloadAccountExport"
  | "downloadShare"
  | "exchangeBootstrapToken"
  | "exchangeGitHubOidc"
  | "failWebYardDeploy"
  | "finaliseWebYardDeploy"
  | "getRetention"
  | "getRetentionOverview"
  | "getUploadStatus"
  | "listAuditEvents"
  | "listCiTrusts"
  | "listInboxes"
  | "listInvites"
  | "listMembers"
  | "listObjects"
  | "listPreviews"
  | "listProjects"
  | "listShares"
  | "listWebYardDeploys"
  | "listWebYards"
  | "logoutCliSession"
  | "pollDeviceLogin"
  | "prepareAccountDeletion"
  | "redeemOneTimeSecret"
  | "refreshCliSession"
  | "removeMember"
  | "renameWorkspace"
  | "requestAccountExport"
  | "requestDownload"
  | "requestUpload"
  | "requestUploadParts"
  | "resolveInbox"
  | "resolveShare"
  | "retryAccountDeletion"
  | "revokeApiToken"
  | "revokeCiTrust"
  | "revokeCliSession"
  | "revokeInbox"
  | "revokeInvite"
  | "revokePreview"
  | "revokeShare"
  | "rollbackWebYard"
  | "setRetention"
  | "startDeviceLogin"
  | "startWebYardDeploy"
  | "updateMemberRole";
export type OptionalOperationId =
  | "getAccountDeletion"
  | "getAccountExport"
  | "getBilling"
  | "health"
  | "listApiTokens"
  | "listCliSessions"
  | "listWorkspaces"
  | "whoAmI";
export interface OperationInputs {
  readonly abortUpload: AbortUploadInput;
  readonly clearRetention: ClearRetentionInput;
  readonly completeAccountDeletion: CompleteAccountDeletionInput;
  readonly completeUpload: CompleteUploadInput;
  readonly createApiToken: CreateApiTokenInput;
  readonly createBillingCheckout: CreateBillingCheckoutInput;
  readonly createBillingPortal: CreateBillingPortalInput;
  readonly createBillingSubscriptionUpdate: CreateBillingSubscriptionUpdateInput;
  readonly createCiTrust: CreateCiTrustInput;
  readonly createInbox: CreateInboxInput;
  readonly createInvite: CreateInviteInput;
  readonly createOneTimeSecret: CreateOneTimeSecretInput;
  readonly createPreview: CreatePreviewInput;
  readonly createProject: CreateProjectInput;
  readonly createShare: CreateShareInput;
  readonly createStorageCheckout: CreateStorageCheckoutInput;
  readonly createStorageUpdate: CreateStorageUpdateInput;
  readonly createWorkspace: CreateWorkspaceInput;
  readonly deleteObject: DeleteObjectInput;
  readonly deleteWebYard: DeleteWebYardInput;
  readonly downloadAccountExport: DownloadAccountExportInput;
  readonly downloadShare: DownloadShareInput;
  readonly exchangeBootstrapToken: ExchangeBootstrapTokenInput;
  readonly exchangeGitHubOidc: ExchangeGitHubOidcInput;
  readonly failWebYardDeploy: FailWebYardDeployInput;
  readonly finaliseWebYardDeploy: FinaliseWebYardDeployInput;
  readonly getAccountDeletion: GetAccountDeletionInput;
  readonly getAccountExport: GetAccountExportInput;
  readonly getBilling: GetBillingInput;
  readonly getRetention: GetRetentionInput;
  readonly getRetentionOverview: GetRetentionOverviewInput;
  readonly getUploadStatus: GetUploadStatusInput;
  readonly health: HealthInput;
  readonly listApiTokens: ListApiTokensInput;
  readonly listAuditEvents: ListAuditEventsInput;
  readonly listCiTrusts: ListCiTrustsInput;
  readonly listCliSessions: ListCliSessionsInput;
  readonly listInboxes: ListInboxesInput;
  readonly listInvites: ListInvitesInput;
  readonly listMembers: ListMembersInput;
  readonly listObjects: ListObjectsInput;
  readonly listPreviews: ListPreviewsInput;
  readonly listProjects: ListProjectsInput;
  readonly listShares: ListSharesInput;
  readonly listWebYardDeploys: ListWebYardDeploysInput;
  readonly listWebYards: ListWebYardsInput;
  readonly listWorkspaces: ListWorkspacesInput;
  readonly logoutCliSession: LogoutCliSessionInput;
  readonly pollDeviceLogin: PollDeviceLoginInput;
  readonly prepareAccountDeletion: PrepareAccountDeletionInput;
  readonly redeemOneTimeSecret: RedeemOneTimeSecretInput;
  readonly refreshCliSession: RefreshCliSessionInput;
  readonly removeMember: RemoveMemberInput;
  readonly renameWorkspace: RenameWorkspaceInput;
  readonly requestAccountExport: RequestAccountExportInput;
  readonly requestDownload: RequestDownloadInput;
  readonly requestUpload: RequestUploadInput;
  readonly requestUploadParts: RequestUploadPartsInput;
  readonly resolveInbox: ResolveInboxInput;
  readonly resolveShare: ResolveShareInput;
  readonly retryAccountDeletion: RetryAccountDeletionInput;
  readonly revokeApiToken: RevokeApiTokenInput;
  readonly revokeCiTrust: RevokeCiTrustInput;
  readonly revokeCliSession: RevokeCliSessionInput;
  readonly revokeInbox: RevokeInboxInput;
  readonly revokeInvite: RevokeInviteInput;
  readonly revokePreview: RevokePreviewInput;
  readonly revokeShare: RevokeShareInput;
  readonly rollbackWebYard: RollbackWebYardInput;
  readonly setRetention: SetRetentionInput;
  readonly startDeviceLogin: StartDeviceLoginInput;
  readonly startWebYardDeploy: StartWebYardDeployInput;
  readonly updateMemberRole: UpdateMemberRoleInput;
  readonly whoAmI: WhoAmIInput;
}
export interface OperationOutputs {
  readonly abortUpload: Schemas["AbortUploadResult"];
  readonly clearRetention: Schemas["ClearRetentionResult"];
  readonly completeAccountDeletion: Schemas["CompleteAccountDeletionResult"];
  readonly completeUpload: Schemas["CompleteUploadResult"];
  readonly createApiToken: Schemas["CreateApiTokenResult"];
  readonly createBillingCheckout: Schemas["CreateBillingCheckoutResult"];
  readonly createBillingPortal: Schemas["CreateBillingPortalResult"];
  readonly createBillingSubscriptionUpdate: Schemas["CreateBillingSubscriptionUpdateResult"];
  readonly createCiTrust: Schemas["CreateCiTrustResult"];
  readonly createInbox: Schemas["CreateInboxResult"];
  readonly createInvite: Schemas["CreateInviteResult"];
  readonly createOneTimeSecret: Schemas["CreateOneTimeSecretResult"];
  readonly createPreview: Schemas["CreatePreviewResult"];
  readonly createProject: Schemas["CreateProjectResult"];
  readonly createShare: Schemas["CreateShareResult"];
  readonly createStorageCheckout: Schemas["CreateStorageCheckoutResult"];
  readonly createStorageUpdate: Schemas["CreateStorageUpdateResult"];
  readonly createWorkspace: Schemas["CreateWorkspaceResult"];
  readonly deleteObject: Schemas["DeleteObjectResult"];
  readonly deleteWebYard: Schemas["DeleteWebYardResult"];
  readonly downloadAccountExport: Schemas["DownloadAccountExportResult"];
  readonly downloadShare: Schemas["DownloadShareResult"];
  readonly exchangeBootstrapToken: Schemas["ExchangeBootstrapTokenResult"];
  readonly exchangeGitHubOidc: Schemas["ExchangeGitHubOidcResult"];
  readonly failWebYardDeploy: Schemas["FailWebYardDeployResult"];
  readonly finaliseWebYardDeploy: Schemas["FinaliseWebYardDeployResult"];
  readonly getAccountDeletion: Schemas["GetAccountDeletionResult"];
  readonly getAccountExport: Schemas["GetAccountExportResult"];
  readonly getBilling: Schemas["GetBillingResult"];
  readonly getRetention: Schemas["GetRetentionResult"];
  readonly getRetentionOverview: Schemas["GetRetentionOverviewResult"];
  readonly getUploadStatus: Schemas["GetUploadStatusResult"];
  readonly health: Schemas["HealthResult"];
  readonly listApiTokens: Schemas["ListApiTokensResult"];
  readonly listAuditEvents: Schemas["ListAuditEventsResult"];
  readonly listCiTrusts: Schemas["ListCiTrustsResult"];
  readonly listCliSessions: Schemas["ListCliSessionsResult"];
  readonly listInboxes: Schemas["ListInboxesResult"];
  readonly listInvites: Schemas["ListInvitesResult"];
  readonly listMembers: Schemas["ListMembersResult"];
  readonly listObjects: Schemas["ListObjectsResult"];
  readonly listPreviews: Schemas["ListPreviewsResult"];
  readonly listProjects: Schemas["ListProjectsResult"];
  readonly listShares: Schemas["ListSharesResult"];
  readonly listWebYardDeploys: Schemas["ListWebYardDeploysResult"];
  readonly listWebYards: Schemas["ListWebYardsResult"];
  readonly listWorkspaces: Schemas["ListWorkspacesResult"];
  readonly logoutCliSession: Schemas["LogoutCliSessionResult"];
  readonly pollDeviceLogin: Schemas["PollDeviceLoginResult"];
  readonly prepareAccountDeletion: Schemas["PrepareAccountDeletionResult"];
  readonly redeemOneTimeSecret: Schemas["RedeemOneTimeSecretResult"];
  readonly refreshCliSession: Schemas["RefreshCliSessionResult"];
  readonly removeMember: Schemas["RemoveMemberResult"];
  readonly renameWorkspace: Schemas["RenameWorkspaceResult"];
  readonly requestAccountExport: Schemas["RequestAccountExportResult"];
  readonly requestDownload: Schemas["RequestDownloadResult"];
  readonly requestUpload: Schemas["RequestUploadResult"];
  readonly requestUploadParts: Schemas["RequestUploadPartsResult"];
  readonly resolveInbox: Schemas["ResolveInboxResult"];
  readonly resolveShare: Schemas["ResolveShareResult"];
  readonly retryAccountDeletion: Schemas["RetryAccountDeletionResult"];
  readonly revokeApiToken: Schemas["RevokeApiTokenResult"];
  readonly revokeCiTrust: Schemas["RevokeCiTrustResult"];
  readonly revokeCliSession: Schemas["RevokeCliSessionResult"];
  readonly revokeInbox: Schemas["RevokeInboxResult"];
  readonly revokeInvite: Schemas["RevokeInviteResult"];
  readonly revokePreview: Schemas["RevokePreviewResult"];
  readonly revokeShare: Schemas["RevokeShareResult"];
  readonly rollbackWebYard: Schemas["RollbackWebYardResult"];
  readonly setRetention: Schemas["SetRetentionResult"];
  readonly startDeviceLogin: Schemas["StartDeviceLoginResult"];
  readonly startWebYardDeploy: Schemas["StartWebYardDeployResult"];
  readonly updateMemberRole: Schemas["UpdateMemberRoleResult"];
  readonly whoAmI: Schemas["WhoAmIResult"];
}
export interface OperationBindings {
  readonly abortUpload: (options: AbortUploadInput) => Promise<OperationOutputs["abortUpload"]>;
  readonly clearRetention: (
    options: ClearRetentionInput,
  ) => Promise<OperationOutputs["clearRetention"]>;
  readonly completeAccountDeletion: (
    options: CompleteAccountDeletionInput,
  ) => Promise<OperationOutputs["completeAccountDeletion"]>;
  readonly completeUpload: (
    options: CompleteUploadInput,
  ) => Promise<OperationOutputs["completeUpload"]>;
  readonly createApiToken: (
    options: CreateApiTokenInput,
  ) => Promise<OperationOutputs["createApiToken"]>;
  readonly createBillingCheckout: (
    options: CreateBillingCheckoutInput,
  ) => Promise<OperationOutputs["createBillingCheckout"]>;
  readonly createBillingPortal: (
    options: CreateBillingPortalInput,
  ) => Promise<OperationOutputs["createBillingPortal"]>;
  readonly createBillingSubscriptionUpdate: (
    options: CreateBillingSubscriptionUpdateInput,
  ) => Promise<OperationOutputs["createBillingSubscriptionUpdate"]>;
  readonly createCiTrust: (
    options: CreateCiTrustInput,
  ) => Promise<OperationOutputs["createCiTrust"]>;
  readonly createInbox: (options: CreateInboxInput) => Promise<OperationOutputs["createInbox"]>;
  readonly createInvite: (options: CreateInviteInput) => Promise<OperationOutputs["createInvite"]>;
  readonly createOneTimeSecret: (
    options: CreateOneTimeSecretInput,
  ) => Promise<OperationOutputs["createOneTimeSecret"]>;
  readonly createPreview: (
    options: CreatePreviewInput,
  ) => Promise<OperationOutputs["createPreview"]>;
  readonly createProject: (
    options: CreateProjectInput,
  ) => Promise<OperationOutputs["createProject"]>;
  readonly createShare: (options: CreateShareInput) => Promise<OperationOutputs["createShare"]>;
  readonly createStorageCheckout: (
    options: CreateStorageCheckoutInput,
  ) => Promise<OperationOutputs["createStorageCheckout"]>;
  readonly createStorageUpdate: (
    options: CreateStorageUpdateInput,
  ) => Promise<OperationOutputs["createStorageUpdate"]>;
  readonly createWorkspace: (
    options: CreateWorkspaceInput,
  ) => Promise<OperationOutputs["createWorkspace"]>;
  readonly deleteObject: (options: DeleteObjectInput) => Promise<OperationOutputs["deleteObject"]>;
  readonly deleteWebYard: (
    options: DeleteWebYardInput,
  ) => Promise<OperationOutputs["deleteWebYard"]>;
  readonly downloadAccountExport: (
    options: DownloadAccountExportInput,
  ) => Promise<OperationOutputs["downloadAccountExport"]>;
  readonly downloadShare: (
    options: DownloadShareInput,
  ) => Promise<OperationOutputs["downloadShare"]>;
  readonly exchangeBootstrapToken: (
    options: ExchangeBootstrapTokenInput,
  ) => Promise<OperationOutputs["exchangeBootstrapToken"]>;
  readonly exchangeGitHubOidc: (
    options: ExchangeGitHubOidcInput,
  ) => Promise<OperationOutputs["exchangeGitHubOidc"]>;
  readonly failWebYardDeploy: (
    options: FailWebYardDeployInput,
  ) => Promise<OperationOutputs["failWebYardDeploy"]>;
  readonly finaliseWebYardDeploy: (
    options: FinaliseWebYardDeployInput,
  ) => Promise<OperationOutputs["finaliseWebYardDeploy"]>;
  readonly getAccountDeletion: (
    options?: GetAccountDeletionInput,
  ) => Promise<OperationOutputs["getAccountDeletion"]>;
  readonly getAccountExport: (
    options?: GetAccountExportInput,
  ) => Promise<OperationOutputs["getAccountExport"]>;
  readonly getBilling: (options?: GetBillingInput) => Promise<OperationOutputs["getBilling"]>;
  readonly getRetention: (options: GetRetentionInput) => Promise<OperationOutputs["getRetention"]>;
  readonly getRetentionOverview: (
    options: GetRetentionOverviewInput,
  ) => Promise<OperationOutputs["getRetentionOverview"]>;
  readonly getUploadStatus: (
    options: GetUploadStatusInput,
  ) => Promise<OperationOutputs["getUploadStatus"]>;
  readonly health: (options?: HealthInput) => Promise<OperationOutputs["health"]>;
  readonly listApiTokens: (
    options?: ListApiTokensInput,
  ) => Promise<OperationOutputs["listApiTokens"]>;
  readonly listAuditEvents: (
    options: ListAuditEventsInput,
  ) => Promise<OperationOutputs["listAuditEvents"]>;
  readonly listCiTrusts: (options: ListCiTrustsInput) => Promise<OperationOutputs["listCiTrusts"]>;
  readonly listCliSessions: (
    options?: ListCliSessionsInput,
  ) => Promise<OperationOutputs["listCliSessions"]>;
  readonly listInboxes: (options: ListInboxesInput) => Promise<OperationOutputs["listInboxes"]>;
  readonly listInvites: (options: ListInvitesInput) => Promise<OperationOutputs["listInvites"]>;
  readonly listMembers: (options: ListMembersInput) => Promise<OperationOutputs["listMembers"]>;
  readonly listObjects: (options: ListObjectsInput) => Promise<OperationOutputs["listObjects"]>;
  readonly listPreviews: (options: ListPreviewsInput) => Promise<OperationOutputs["listPreviews"]>;
  readonly listProjects: (options: ListProjectsInput) => Promise<OperationOutputs["listProjects"]>;
  readonly listShares: (options: ListSharesInput) => Promise<OperationOutputs["listShares"]>;
  readonly listWebYardDeploys: (
    options: ListWebYardDeploysInput,
  ) => Promise<OperationOutputs["listWebYardDeploys"]>;
  readonly listWebYards: (options: ListWebYardsInput) => Promise<OperationOutputs["listWebYards"]>;
  readonly listWorkspaces: (
    options?: ListWorkspacesInput,
  ) => Promise<OperationOutputs["listWorkspaces"]>;
  readonly logoutCliSession: (
    options: LogoutCliSessionInput,
  ) => Promise<OperationOutputs["logoutCliSession"]>;
  readonly pollDeviceLogin: (
    options: PollDeviceLoginInput,
  ) => Promise<OperationOutputs["pollDeviceLogin"]>;
  readonly prepareAccountDeletion: (
    options: PrepareAccountDeletionInput,
  ) => Promise<OperationOutputs["prepareAccountDeletion"]>;
  readonly redeemOneTimeSecret: (
    options: RedeemOneTimeSecretInput,
  ) => Promise<OperationOutputs["redeemOneTimeSecret"]>;
  readonly refreshCliSession: (
    options: RefreshCliSessionInput,
  ) => Promise<OperationOutputs["refreshCliSession"]>;
  readonly removeMember: (options: RemoveMemberInput) => Promise<OperationOutputs["removeMember"]>;
  readonly renameWorkspace: (
    options: RenameWorkspaceInput,
  ) => Promise<OperationOutputs["renameWorkspace"]>;
  readonly requestAccountExport: (
    options: RequestAccountExportInput,
  ) => Promise<OperationOutputs["requestAccountExport"]>;
  readonly requestDownload: (
    options: RequestDownloadInput,
  ) => Promise<OperationOutputs["requestDownload"]>;
  readonly requestUpload: (
    options: RequestUploadInput,
  ) => Promise<OperationOutputs["requestUpload"]>;
  readonly requestUploadParts: (
    options: RequestUploadPartsInput,
  ) => Promise<OperationOutputs["requestUploadParts"]>;
  readonly resolveInbox: (options: ResolveInboxInput) => Promise<OperationOutputs["resolveInbox"]>;
  readonly resolveShare: (options: ResolveShareInput) => Promise<OperationOutputs["resolveShare"]>;
  readonly retryAccountDeletion: (
    options: RetryAccountDeletionInput,
  ) => Promise<OperationOutputs["retryAccountDeletion"]>;
  readonly revokeApiToken: (
    options: RevokeApiTokenInput,
  ) => Promise<OperationOutputs["revokeApiToken"]>;
  readonly revokeCiTrust: (
    options: RevokeCiTrustInput,
  ) => Promise<OperationOutputs["revokeCiTrust"]>;
  readonly revokeCliSession: (
    options: RevokeCliSessionInput,
  ) => Promise<OperationOutputs["revokeCliSession"]>;
  readonly revokeInbox: (options: RevokeInboxInput) => Promise<OperationOutputs["revokeInbox"]>;
  readonly revokeInvite: (options: RevokeInviteInput) => Promise<OperationOutputs["revokeInvite"]>;
  readonly revokePreview: (
    options: RevokePreviewInput,
  ) => Promise<OperationOutputs["revokePreview"]>;
  readonly revokeShare: (options: RevokeShareInput) => Promise<OperationOutputs["revokeShare"]>;
  readonly rollbackWebYard: (
    options: RollbackWebYardInput,
  ) => Promise<OperationOutputs["rollbackWebYard"]>;
  readonly setRetention: (options: SetRetentionInput) => Promise<OperationOutputs["setRetention"]>;
  readonly startDeviceLogin: (
    options: StartDeviceLoginInput,
  ) => Promise<OperationOutputs["startDeviceLogin"]>;
  readonly startWebYardDeploy: (
    options: StartWebYardDeployInput,
  ) => Promise<OperationOutputs["startWebYardDeploy"]>;
  readonly updateMemberRole: (
    options: UpdateMemberRoleInput,
  ) => Promise<OperationOutputs["updateMemberRole"]>;
  readonly whoAmI: (options?: WhoAmIInput) => Promise<OperationOutputs["whoAmI"]>;
}
export declare function bindOperations(
  request: <Id extends OperationId>(
    operationId: Id,
    options: OperationInputs[Id],
  ) => Promise<OperationOutputs[Id]>,
): OperationBindings;
