mod auth;
mod inboxes;
mod lifecycle;
mod local_users;
mod metadata;
mod previews;
mod sharing;
mod transfer;
mod yard_access;
mod yard_sessions;
mod yards;

use std::sync::atomic::AtomicUsize;

#[derive(Clone, Copy, Debug)]
pub(crate) enum Corruption {
    SchemaVersion,
    WorkspaceList,
    WorkspaceRecord,
    RenamedWorkspaceList,
    RenamedWorkspaceRecord,
    ProjectList,
    ProjectRecord,
    CompleteState,
    CompleteSize,
    CompleteChecksum,
    AbortedState,
    DownloadList,
    FirstReservationVersion,
    FirstReservationState,
    FirstCapabilityRecord,
    RenewedExpiry,
    CompletedState,
    CompletedVersion,
    SecondReservationVersion,
    LatestLength,
    LatestVersion,
    AllLength,
    AllFirstVersion,
    AllSecondVersion,
    RequestedAbortPrior,
    RequestedAbortStored,
    UploadedAbortPrior,
    UploadedAbortStored,
    DownloadVersion,
    MultipartReservation,
    MultipartAttachment,
    MultipartIssued,
    MultipartResolution,
    MultipartListing,
    MultipartCompletion,
    MultipartAbort,
    BootstrapFirstFalse,
    BootstrapSecondTrue,
    ActiveTokenRecord,
    CreatedTokenRecord,
    MonotonicTokenRecord,
    CliSessionList,
    FinalTokenListError,
    FinalTokenListMismatch,
    TokenList,
    LocalUserInitialList,
    LocalUserFreshAuthentication,
    LocalUserBoundaryAuthentication,
    LocalUserResetAuthentication,
    DeletionComplete,
    DeletionItems,
    DeletionReplayIncomplete,
    RetentionPolicy,
    ClearFalse,
    RetentionStatus,
    AuditPageLength,
    AuditCursor,
    AuditNextLength,
    AuditNextAction,
    ShareCreatedRecord,
    ShareList,
    ShareResolvedTarget,
    ShareIssuedTarget,
    ShareFirstRevoke,
    ShareSecondRevoke,
    ShareFinalRecord,
    ShareFinalList,
    InboxCreatedRecord,
    InboxList,
    InboxResolvedRecord,
    InboxRateAllowed,
    InboxRateLimited,
    InboxRateReset,
    InboxReservedRecord,
    InboxReservedList,
    InboxReservedCounters,
    InboxCompletedRecord,
    InboxCompletedList,
    InboxCompletedCounters,
    InboxAbortPrior,
    InboxAbortStored,
    InboxCapacityResult,
    InboxReleasedList,
    InboxReleasedCounters,
    InboxExpiryResult,
    InboxFirstRevoke,
    InboxSecondRevoke,
    InboxRevokedResolve,
    PreviewInitialList,
    PreviewObjectList,
    PreviewCreatedRecord,
    PreviewResolvedTarget,
    PreviewList,
    PreviewMissingResolution,
    PreviewExpiredResolution,
    PreviewFirstRevoke,
    PreviewSecondRevoke,
    PreviewRevokedResolution,
    YardInitialList,
    YardEnvironmentList,
    YardUnknownEnvironmentList,
    YardFixtureObjectList,
    YardReusedStart,
    YardReplacementStatus,
    YardDelayedStatus,
    YardRollbackRecord,
    YardFailureRecord,
    YardListShape,
    YardDeliveryTarget,
    YardFirstDelete,
    YardSecondDelete,
    YardFinalRecord,
    YardDeletedResolution,
    YardPhantomPolicy,
    YardPhantomGrantList,
    YardUnknownGrantList,
    YardVisibilityRecord,
    YardRestoredVisibility,
    YardPrivateDelivery,
    YardGrantRecord,
    YardScopedGrantRecord,
    YardGrantValidation,
    YardExpiredGrantList,
    YardRevokedGrantList,
    YardMissingGrantRevoke,
    YardFirstRevoke,
    YardSecondRevoke,
    YardGrantListOrder,
    YardAccessEnvironmentSeed,
    YardSessionAdmission,
    YardSessionExchange,
    YardSessionList,
    YardSessionFirstRevoke,
    YardSessionLogoutRevoke,
}

pub(crate) struct Corrupting<'a, T> {
    inner: &'a T,
    corruption: Corruption,
    inbox_list_calls: AtomicUsize,
    environment_list_calls: AtomicUsize,
}

impl<'a, T> Corrupting<'a, T> {
    pub(crate) const fn new(inner: &'a T, corruption: Corruption) -> Self {
        Self {
            inner,
            corruption,
            inbox_list_calls: AtomicUsize::new(0),
            environment_list_calls: AtomicUsize::new(0),
        }
    }
}
